Updated runtime for Golang since AWS no longer supports nodejs 0.10 Just changed runtime string only not stubs(index.js, ...)
InvalidParameterValueException: The runtime parameter of nodejs is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs4.3) while creating or updating functions.